- hosts: gitbucket
  user: root
  become: no

  tasks:
    - file:
        path: /opt/compose/gitbucket
        state: directory

    - name: install docker-compose gitbucket file
      template:
        src: service/gitbucket/docker-compose.yml.j2
        dest: /opt/compose/gitbucket/docker-compose.yml

    - copy:
        src: dc@.service
        dest: /usr/lib/systemd/system/dc@.service

    - name: start and enabled gitbucket service
      systemd:
        name: dc@gitbucket
        enabled: yes
        state: started

